### PR TITLE
Selenium tests working locally

### PR DESCRIPTION
**Pull request by digitalfishpond**
The tests now work locally from a computer within FJ Proxy.

---
This change is [Reviewable](https://reviewable.io/reviews/nephologyfj/nephology/61)

### CODE REVIEW

**Comment by digitalfishpond** [comment]
@grubskim  please review

**Comment by grubskim** [comment]
@digitalfishpond 
I have tested it and it works, which is awesome :)

Couple things have to be cleaned up:
.travis.yml
```
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
```
Should be removed - tests are not being run in travis anyway.

pom.xml
```
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
```
Should be removed - unneeded dependency

`log4j.properties` - (file) is it needed?

TestResourcesStaticIndex.java
```
 Proxy proxy = new Proxy();
 proxy.setHttpProxy("xxxxxx");
  driver.setProxySettings(proxy);
```
Should be removed - we can't expose this proxy. For now do not use proxy at all. I will on a better way to read properties in the next sprint as this is clearly a big problem right now.

**Comment by digitalfishpond** [comment]
PTAL

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nephologyfj/nephology/61#-:-KfuTNAZMQzWWEv3xh_8:bb71pro)*

**Comment by grubskim** [comment]
Reviewed 2 of 6 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/nephology/webtest/TestResourcesStaticIndex.java, line 23 at r1](https://reviewable.io:443/reviews/nephologyfj/nephology/61#-Kfqcb8Q8gLC56EqCDZM:-Kfqcb8Q8gLC56EqCDZN:br7fuu8) ([raw file](https://github.com/nephologyfj/nephology/blob/a9d341244b84168f0d187dfc466a19e2a03da994/src/test/nephology/webtest/TestResourcesStaticIndex.java#L23)):*
>  Proxy proxy = new Proxy();
>         proxy.setHttpProxy("abgproxya.abg.fsc.net:82");

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nephologyfj/nephology/61)*

**Comment by grubskim** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nephologyfj/nephology/61#-:-KfuVwUOSmtQ0RoSjVS0:bnfp4nl)*

**Comment by grubskim** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nephologyfj/nephology/61)*

**Comment by digitalfishpond** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/nephology/webtest/TestResourcesStaticIndex.java, line 23 at r1](https://reviewable.io:443/reviews/nephologyfj/nephology/61#-Kfqcb8Q8gLC56EqCDZM:-KfuWOxqNdJpEQTD8eHj:b-896fix) ([raw file](https://github.com/nephologyfj/nephology/blob/a9d341244b84168f0d187dfc466a19e2a03da994/src/test/nephology/webtest/TestResourcesStaticIndex.java#L23)):*
<details><summary><i>Previously, grubskim (Michał Grubski) wrote…</i></summary><blockquote>

>  Proxy proxy = new Proxy();
>         proxy.setHttpProxy("abgproxya.abg.fsc.net:82");

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nephologyfj/nephology/61)*

**Pull request merged**
