### PR TITLE
Security hotfix

### PR DESCRIPTION
**Pull request by victorhrsilva**
Removed all tokens and api keys from Travis and Application.Properties

---
This change is [Reviewable](https://reviewable.io/reviews/nephologyfj/nephology/56)

### CODE REVIEW

**Comment by digitalfishpond** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[.travis.yml, line 15 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38_owj0UdYoCfUoZ-:-Kf38_owj0UdYoCfUoZ0:b-6hjt9) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/.travis.yml#L15)):*
> ```YAML
>     branches:
>       - master
>   script:
> ```

is this space intentional?

---

*[src/main/java/nephology/Application.java, line 3 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38oo7igTb601VKDeZ:-Kf38oo7igTb601VKDe_:b951igj) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Application.java#L3)):*
> ```Java
> package nephology;
> ```

is this extra line intentional?

---

*[src/main/java/nephology/Security.java, line 8 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38s7-MEP2BKTGmdm3:-Kf38s7-MEP2BKTGmdm4:bb7od0r) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Security.java#L8)):*
> ```Java
> import org.springframework.security.config.annotation.web.builders.HttpSecurity;
> import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
> ```

same

---

*[src/main/java/nephology/Security.java, line 22 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38tUrjEE6gNkPcg0a:-Kf38tUrjEE6gNkPcg0b:b-4nq930) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Security.java#L22)):*
> ```Java
>     @Override
>     protected void configure(HttpSecurity http) throws Exception {
> ```

same :)

---

*[src/main/java/nephology/Security.java, line 24 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38utJDadF7BpVLn7M:-Kf38utJDadF7BpVLn7N:b2ngvnt) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Security.java#L24)):*
> ```Java
> 
>         http
>                 .apply(stormpath());
> ```

...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nephologyfj/nephology/56)*

**Comment by victorhrsilva** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 15 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38_owj0UdYoCfUoZ-:-Kf69RHIBLLJp4Gl2oRy:bg8m80w) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/.travis.yml#L15)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary><blockquote>

is this space intentional?
</blockquote></details>

This space was intentional, because I thought that script belongs to the sonarqube addon, but turns out that it is a totally different tag. I will fix it.

---

*[src/main/java/nephology/Application.java, line 3 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38oo7igTb601VKDeZ:-Kf6AR5M5DKPPFCAP4OA:ba4svxu) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Application.java#L3)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary><blockquote>

is this extra line intentional?
</blockquote></details>

I will remove this extra line.

---

*[src/main/java/nephology/Security.java, line 8 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38s7-MEP2BKTGmdm3:-Kf6AVOc6aJcBX74r9Oc:bbe93w) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Security.java#L8)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary><blockquote>

same
</blockquote></details>

I will remove it also.

---

*[src/main/java/nephology/Security.java, line 22 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38tUrjEE6gNkPcg0a:-Kf6AXdCxsDLukh03a6N:b-b9zzs6) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Security.java#L22)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary><blockquote>

same :)
</blockquote></details>

I will remote it also.

---

*[src/main/java/nephology/Security.java, line 24 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38utJDadF7BpVLn7M:-Kf6A_cD2urF4fOYl80a:b2ngvnt) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Security.java#L24)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary><blockquote>

...
</blockquote></details>

...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nephologyfj/nephology/56)*

**Comment by victorhrsilva** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[.travis.yml, line 15 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38_owj0UdYoCfUoZ-:-Kf6MY62XNfw5LbX0TwP:b-896fix) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/.travis.yml#L15)):*
<details><summary><i>Previously, victorhrsilva wrote…</i></summary><blockquote>

This space was intentional, because I thought that script belongs to the sonarqube addon, but turns out that it is a totally different tag. I will fix it.
</blockquote></details>

Done.

---

*[src/main/java/nephology/Security.java, line 8 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38s7-MEP2BKTGmdm3:-Kf6MahtW0HAdGfEwKqc:b-896fix) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Security.java#L8)):*
<details><summary><i>Previously, victorhrsilva wrote…</i></summary><blockquote>

I will remove it also.
</blockquote></details>

Done.

---

*[src/main/java/nephology/Security.java, line 22 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38tUrjEE6gNkPcg0a:-Kf6Mc17Rh-3joUL3YAy:b-896fix) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Security.java#L22)):*
<details><summary><i>Previously, victorhrsilva wrote…</i></summary><blockquote>

I will remote it also.
</blockquote></details>

Done.

---

*[src/main/java/nephology/Security.java, line 24 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38utJDadF7BpVLn7M:-Kf6McT-xHcTZS5n67jl:b-896fix) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Security.java#L24)):*
<details><summary><i>Previously, victorhrsilva wrote…</i></summary><blockquote>

...
</blockquote></details>

Done.

---

*[src/main/java/nephology/Application.java, line 3 at r3](https://reviewable.io:443/reviews/nephologyfj/nephology/56#-Kf38oo7igTb601VKDeZ:-Kf6MdFsRFlYr5dtVhJ2:b-896fix) ([raw file](https://github.com/nephologyfj/nephology/blob/31036a4b70992554edd27e009bb46f475070ebc4/src/main/java/nephology/Application.java#L3)):*
<details><summary><i>Previously, victorhrsilva wrote…</i></summary><blockquote>

I will remove this extra line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nephologyfj/nephology/56)*

**Comment by grubskim** [comment]
Reviewed 1 of 6 files at r1, 2 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nephologyfj/nephology/56)*

**Pull request merged**
